[package]
name = "interlocking-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec_simd = "0.20.5"
chrono = "0.4.31"
itertools = "0.12.0"
rand = "0.8.5"
